### ISSUE TITLE
[EPIC] Easy to start and to use demo examples & clusters (AWS, GCP, Azure)

### ISSUE THREAD

**Issue by alinaignatiuk** [odahu/odahu-examples#51]
Check list of tasks in the issues description

**Comment by alinaignatiuk** [comment]
- [ ] Check Reuters example in the main examples repository and the other one and delete separate repository - @BPylypenko 
- [x] Test all ODAHU examples in examples repository, create high-level [test plan on kb](https://kb.epam.com/display/EPMCBDCC/%5BODAHU%5D+Tests+Check+list) - @BPylypenko 
- [ ] Create/update demo scenarios for each example - @alinaignatiuk  & @viravit 
- [ ] Add instruction how to start and stop ODAHU demo clusters [on kb ](https://kb.epam.com/display/EPMCBDCC/ODAHU+Cluster+Start+and+Stop) - @alinaignatiuk  & @viravit
